import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const endpoint = 'https://contact-worker.meiteya.workers.dev';
const items = [['PROFILE','About'],['TOOL','Works'],['NOTE','Writing'],['IDEA','Experiment'],['LINK','Social'],['CONTACT','Message']];
const ideas = [['Bottom to Top','./idea/design_bottom_to_top/'],['Fuwafuwa','./idea/design_fuwafuwa/'],['Neko','./idea/design_neko/'],['Terminal','./idea/design_terminal/'],['Specimen','./idea/design_specimen/']];
function useClock(){const [v,setV]=useState('JST --:--');useEffect(()=>{const f=()=>setV(`JST ${new Intl.DateTimeFormat('ja-JP',{timeZone:'Asia/Tokyo',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date())}`);f();const i=setInterval(f,30000);return()=>clearInterval(i)},[]);return v}
function Links({links}){return <div className="feature-list">{links.map(([label,href])=><a className="feature-link" href={href} key={href}><span>{label}</span><b>OPEN <i>↗</i></b></a>)}</div>}
function Modal({name,onClose}){const [status,setStatus]=useState('');const [notes,setNotes]=useState([]);const number=items.findIndex(x=>x[0]===name)+1;useEffect(()=>{if(name==='NOTE')fetch('./note/index.json',{cache:'no-store'}).then(r=>r.json()).then(setNotes).catch(()=>setStatus('ノート一覧を読み込めませんでした。'))},[name]);useEffect(()=>{const f=e=>e.key==='Escape'&&onClose();document.addEventListener('keydown',f);return()=>document.removeEventListener('keydown',f)},[onClose]);const submit=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));if(!data.name||!data.email||!data.message)return setStatus('すべての項目を入力してください。');setStatus('送信中...');try{const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});if(!r.ok)throw Error();e.currentTarget.reset();setStatus('送信しました。')}catch{setStatus('送信できませんでした。時間をおいて再度お試しください。')}};return <div className="modal is-open"><button className="modal__backdrop" onClick={onClose} aria-label="閉じる"/><section className="modal__panel" role="dialog" aria-modal="true" aria-labelledby="modal-title"><div className="modal__header"><p>{String(number).padStart(2,'0')} / 06</p><button className="modal__close" onClick={onClose} aria-label="閉じる">×</button></div><div className="modal__body"><p className="modal__label">{items[number-1][1]}</p><h2 id="modal-title">{name}</h2>{name==='PROFILE'&&<><p className="modal__lead">Webの技術を使って、日常で役立つものや面白い体験をつくっています。</p><div className="profile-grid"><dl><dt>Name</dt><dd>ak-2302</dd></dl><dl><dt>Location</dt><dd>Japan</dd></dl><dl><dt>Focus</dt><dd>Web Development</dd></dl></div></>}{name==='TOOL'&&<><p className="modal__lead">手軽に使える道具をつくっています。</p><Links links={[["Web tools",'./tool/']]}/></>}{name==='NOTE'&&<Links links={notes.map(n=>[n.title,n.url])}/>} {name==='IDEA'&&<><p className="modal__lead">まだ形になっていない、ユニークなアイデアを集める場所です。</p><Links links={ideas}/></>}{name==='LINK'&&<nav className="social-links">{[['GitHub','https://github.com/ak-2302'],['Qiita','https://qiita.com/ak-2302'],['Zenn','https://zenn.dev/ak2302'],['X','https://x.com/ak_2302x']].map(([x,h])=><a href={h} target="_blank" rel="noreferrer" key={h}><span>{x}</span><b>↗</b></a>)}</nav>}{name==='CONTACT'&&<form className="contact-form" onSubmit={submit}><label>Name<input name="name" required maxLength="80"/></label><label>Email<input name="email" type="email" required maxLength="254"/></label><label>Message<textarea name="message" rows="4" required maxLength="1800"/></label><div className="contact-form__footer"><p aria-live="polite">{status}</p><button type="submit">SEND MESSAGE <span>↗</span></button></div></form>}</div></section></div>}
function Home(){const [open,setOpen]=useState(null);const clock=useClock();return <main className="site-shell"><header className="site-header"><a className="site-logo" href="./"><span className="site-logo__mark"/>ak-2302</a><p className="site-header__status"><span/> Interactive portfolio</p></header><section className="hero"><div className="hero__copy"><p className="eyebrow">Personal website / 2026</p><p className="hero__description">6つの入り口を、触れて選んでください。</p></div><div className="stage-wrap"><div className="sphere-stage" aria-label="コンテンツメニュー">{items.map(([label,type],i)=><button className={`sphere sphere--${i+1}`} key={label} onClick={()=>setOpen(label)}><strong>{label}</strong><small>AK / 2302</small><em>{type}</em></button>)}</div><div className="stage-hint">CLICK A SPHERE</div></div><p className="hero__index">01 — 06</p></section><footer className="site-footer"><p>© {new Date().getFullYear()} ak-2302</p><p>REACT × VITE</p><time>{clock}</time></footer>{open&&<Modal name={open} onClose={()=>setOpen(null)}/>}</main>}
createRoot(document.getElementById('root')).render(<Home/>);
